In [1]:
import pandas as pd
import folium
import numpy as np

In [2]:
total_points = pd.read_csv('/Users/air/Desktop/Total_point.csv')
total_points.head()

Point_ID   Latitude  Longitude  grid_number  Slow  Fast  Rapid  Total  index
0        0  56.466217  -3.046891           89     0     0      0      0      1
1        1  56.472241  -2.848474          412     0     0      0      0      2
2        2  56.473208  -2.895034          328     0     0      0      0      3
3        3  56.463504  -2.963304          228     0     0      0      0      4
4        4  56.460974  -2.977650          200     0     0      0      0      5

In [3]:
min_cost_data0 = pd.read_excel('/Users/air/Desktop/result/min cost/year 0.xlsx')
point_index0 = total_points[min_cost_data0['point_total']!=0][['Latitude', 'Longitude']]
num_of_point0 = min_cost_data0[min_cost_data0['point_total']!=0]['point_total']
final_data0 = pd.concat([point_index0,num_of_point0],axis=1)

In [4]:
#Year0: current points
tooltip = "Year_0!"
m = folium.Map(location=[final_data0['Latitude'].iloc[0],final_data0['Longitude'].iloc[0]],tooltip=tooltip)

for i in range(0,final_data0.shape[0]):
    if final_data0.iloc[i,2] >=1 and final_data0.iloc[i,2]<=3:
        #fill_color="#F5F5F5"
        radius = 10
        color="#4682B4"
    if final_data0.iloc[i,2] >=4 and final_data0.iloc[i,2] <=7:
        #fill_color="#808069"
        radius = 20
        color="#0000FF"
    if final_data0.iloc[i,2]>=8 and final_data0.iloc[i,2]<=10:
        #fill_color="#000000"
        radius = 30
        color="#191970"
    
    coordinates0= np.array(final_data0.iloc[i,:2])

    folium.Marker(
        location=[coordinates0[0], coordinates0[1]],
        tooltip=tooltip,icon=folium.Icon(color='gray')).add_to(m)

    folium.CircleMarker(
        location=[coordinates0[0],coordinates0[1]],
        radius=radius,
        popup=f"Year_0",
        color=color,
        fill=False,
        fill_color="#F5F5F5",
    ).add_to(m)

In [9]:
m.save("m_cost0.html")

In [10]:
min_cost_data1 = pd.read_excel('/Users/air/Desktop/result/min cost/year 1.xlsx')
point_index1 = total_points[min_cost_data1['point_total']!=0][['Latitude', 'Longitude']]

num_of_point1 = min_cost_data1[min_cost_data1['point_total']!=0]['point_total']

final_data1 = pd.concat([point_index1,num_of_point1],axis=1)

#find the new points coordinates
new_coordinates1 = []
for i in np.array(final_data1.iloc[:,:2]):
    if i not in np.array(final_data0.iloc[:,:2]):
        new_coordinates1.append(i)

In [11]:
#draw the new points in year 1 in red 
for j in range(len(new_coordinates1)): 
    folium.Marker(
            location=[new_coordinates1[j][0], new_coordinates1[j][1]],
            tooltip=tooltip,icon=folium.Icon(color='red')).add_to(m)

In [12]:
#draw the changes from year 0 to year 1
for i in range(0,final_data1.shape[0]):
    if final_data1.iloc[i,2] >=1 and final_data1.iloc[i,2]<=3:
        #fill_color="#F5F5F5"
        radius = 10
        color="#4682B4"
    if final_data1.iloc[i,2] >=4 and final_data1.iloc[i,2] <=7:
        #fill_color="#808069"
        radius = 20
        color="#0000FF"
    if final_data1.iloc[i,2]>=8 and final_data1.iloc[i,2]<=10:
        #fill_color="#000000"
        radius = 30
        color="#191970"
        
    coordinates1= np.array(final_data1.iloc[i,:2])
    
    folium.CircleMarker(
        location=[coordinates1[0],coordinates1[1]],
        radius=radius,
        popup=f"Year_1",
        color=color,
        fill=False,
        fill_color="#F5F5F5",
    ).add_to(m)

In [13]:
m.save("m_cost1.html")

In [14]:
#Year2
min_cost_data2 = pd.read_excel('/Users/air/Desktop/result/min cost/year 2.xlsx')
point_index2 = total_points[min_cost_data2['point_total']!=0][['Latitude', 'Longitude']]

num_of_point2 = min_cost_data2[min_cost_data2['point_total']!=0]['point_total']

final_data2 = pd.concat([point_index2,num_of_point2],axis=1)

#find the new points coordinates
new_coordinates2 = []
for i in np.array(final_data2.iloc[:,:2]):
    if i not in np.array(final_data1.iloc[:,:2]):
        new_coordinates2.append(i)

In [15]:
#draw the new points in year 2 in red 
for j in range(len(new_coordinates2)): 
    folium.Marker(
            location=[new_coordinates2[j][0], new_coordinates2[j][1]],
            tooltip=tooltip,icon=folium.Icon(color='green')).add_to(m)

In [16]:
#draw the changes from year 1 to year 2
for i in range(0,final_data2.shape[0]):
    if final_data2.iloc[i,2] >=1 and final_data2.iloc[i,2]<=3:
        #fill_color="#F5F5F5"
        radius = 10
        color="#4682B4"
    if final_data2.iloc[i,2] >=4 and final_data2.iloc[i,2] <=7:
        #fill_color="#808069"
        radius = 20
        color="#0000FF"
    if final_data2.iloc[i,2]>=8 and final_data2.iloc[i,2]<=10:
        #fill_color="#000000"
        radius = 30
        color="#191970"
        
    coordinates2= np.array(final_data2.iloc[i,:2])
    
    folium.CircleMarker(
        location=[coordinates2[0],coordinates2[1]],
        radius=radius,
        popup=f"Year_2",
        color=color,
        fill=False,
        fill_color="#F5F5F5",
    ).add_to(m)

In [17]:
m.save("m_cost2.html")

In [18]:
#Year3
min_cost_data3 = pd.read_excel('/Users/air/Desktop/result/min cost/year 3.xlsx')
point_index3 = total_points[min_cost_data3['point_total']!=0][['Latitude', 'Longitude']]
num_of_point3 = min_cost_data3[min_cost_data3['point_total']!=0]['point_total']
final_data3 = pd.concat([point_index3,num_of_point3],axis=1)

#find the new points coordinates
new_coordinates3 = []
for i in np.array(final_data3.iloc[:,:2]):
    if i not in np.array(final_data2.iloc[:,:2]):
        new_coordinates3.append(i)

In [19]:
new_coordinates3

[array([56.48689019, -2.95957476]),
 array([56.47341014, -2.93007684]),
 array([56.47446815, -2.89367902]),
 array([56.45363655, -3.01029281])]

In [20]:
#draw the new points in year 3 in  orange
for j in range(len(new_coordinates3)): 
    folium.Marker(
            location=[new_coordinates3[j][0], new_coordinates3[j][1]],
            tooltip=tooltip,icon=folium.Icon(color='orange')).add_to(m)

In [21]:
#draw the changes from year 2 to year 3
for i in range(0,final_data3.shape[0]):
    if final_data3.iloc[i,2] >=1 and final_data3.iloc[i,2]<=3:
        #fill_color="#F5F5F5"
        radius = 10
        color="#4682B4"
    if final_data3.iloc[i,2] >=4 and final_data3.iloc[i,2] <=7:
        #fill_color="#808069"
        radius = 20
        color="#0000FF"
    if final_data3.iloc[i,2]>=8 and final_data3.iloc[i,2]<=10:
        #fill_color="#000000"
        radius = 30
        color="#191970"
        
    coordinates3= np.array(final_data3.iloc[i,:2])
    
    folium.CircleMarker(
        location=[coordinates3[0],coordinates3[1]],
        radius=radius,
        popup=f"Year_3",
        color=color,
        fill=False,
        fill_color="#F5F5F5",
    ).add_to(m)

In [22]:
m.save("m_cost3.html")

In [23]:
#Year4
min_cost_data4 = pd.read_excel('/Users/air/Desktop/result/min cost/year 4.xlsx')
point_index4 = total_points[min_cost_data4['point_total']!=0][['Latitude', 'Longitude']]

num_of_point4 = min_cost_data4[min_cost_data4['point_total']!=0]['point_total']

final_data4 = pd.concat([point_index4,num_of_point4],axis=1)

#find the new points coordinates
new_coordinates4 = []
for i in np.array(final_data4.iloc[:,:2]):
    if i not in np.array(final_data3.iloc[:,:2]):
        new_coordinates4.append(i)

In [260]:
#draw the new points in year 4 in black
for j in range(len(new_coordinates4)): 
    folium.Marker(
            location=[new_coordinates4[j][0], new_coordinates4[j][1]],
            tooltip=tooltip,icon=folium.Icon(color='black')).add_to(m)

In [25]:
#draw the changes from year 3 to year 4
for i in range(0,final_data4.shape[0]):
    if final_data4.iloc[i,2] >=1 and final_data4.iloc[i,2]<=3:
        #fill_color="#F5F5F5"
        radius = 10
        color="#4682B4"
    if final_data4.iloc[i,2] >=4 and final_data4.iloc[i,2] <=7:
        #fill_color="#808069"
        radius = 20
        color="#0000FF"
    if final_data4.iloc[i,2]>=8 and final_data4.iloc[i,2]<=10:
       #fill_color="#000000"
        radius = 30
        color="#191970"
        
    coordinates4= np.array(final_data4.iloc[i,:2])
    
    folium.CircleMarker(
        location=[coordinates4[0],coordinates4[1]],
        radius=radius,
        popup=f"Year_4",
        color=color,
        fill=False,
        fill_color="#F5F5F5",
    ).add_to(m)

In [26]:
m.save("m_cost4.html")

In [5]:
min_interest_data0 = pd.read_excel('/Users/air/Desktop/result/min interest/year 0.xlsx')
min_interest_data1 = pd.read_excel('/Users/air/Desktop/result/min interest/year 1.xlsx')
min_interest_data2 = pd.read_excel('/Users/air/Desktop/result/min interest/year 2.xlsx')
min_interest_data3 = pd.read_excel('/Users/air/Desktop/result/min interest/year 3.xlsx')
min_interest_data4 = pd.read_excel('/Users/air/Desktop/result/min interest/year 4.xlsx')

In [6]:
min_cost_data0 = pd.read_excel('/Users/air/Desktop/result/min cost/year 0.xlsx')
min_cost_data1 = pd.read_excel('/Users/air/Desktop/result/min cost/year 1.xlsx')
min_cost_data2 = pd.read_excel('/Users/air/Desktop/result/min cost/year 2.xlsx')
min_cost_data3 = pd.read_excel('/Users/air/Desktop/result/min cost/year 3.xlsx')
min_cost_data4 = pd.read_excel('/Users/air/Desktop/result/min cost/year 4.xlsx')

In [7]:
def get_data(data):
    point_index = total_points[data['point_total']!=0][['Latitude', 'Longitude']]
    num_of_point = data[data['point_total']!=0]['point_total']
    final_data = pd.concat([point_index,num_of_point],axis=1)
    return final_data 

In [8]:
interest0 = get_data(min_interest_data0)
interest1 = get_data(min_interest_data1)
interest2 = get_data(min_interest_data2)
interest3 = get_data(min_interest_data3)
interest4 = get_data(min_interest_data4)

In [9]:
cost0 = get_data(min_cost_data0)
cost1 = get_data(min_cost_data1)
cost2 = get_data(min_cost_data2)
cost3 = get_data(min_cost_data3)
cost4 = get_data(min_cost_data4)

In [10]:
def start_plot(data,year):
    tooltip = f"Year_{year}!"
    m = folium.Map(location=[data['Latitude'].iloc[0],data['Longitude'].iloc[0]],tooltip=tooltip)

    for i in range(0,data.shape[0]):
        if data.iloc[i,2] >=1 and data.iloc[i,2]<=3:
            radius = 10
            color="#4682B4"
        if data.iloc[i,2] >=4 and data.iloc[i,2] <=7:
            radius = 20
            color="#0000FF"
        if data.iloc[i,2]>=8 and data.iloc[i,2]<=10:
            radius = 30
            color="#191970"

        coordinates= np.array(data.iloc[i,:2])

        folium.Marker(
            location=[coordinates[0], coordinates[1]],
            tooltip=tooltip,icon=folium.Icon(color='gray')).add_to(m)

        folium.CircleMarker(
            location=[coordinates[0],coordinates[1]],
            radius=radius,
            color=color,
            fill=False,
            fill_color="#F5F5F5",
        ).add_to(m)
    return m

In [32]:
m = start_plot(interest0 ,0)
m_cost = start_plot(cost0 ,0)

In [14]:
m.save("current.html")

In [33]:
#find the new points coordinates
def draw_new_points(data1,data0,year,m):
    new_coordinates = []
    for i in np.array(data1.iloc[:,:2]):
        if i not in np.array(data0.iloc[:,:2]):
            new_coordinates.append(i)
            
    color = ['red','green','orange','black']
    tooltip = f"Year_{year}!"
    for j in range(len(new_coordinates)): 
        folium.Marker(
                location=[new_coordinates[j][0], new_coordinates[j][1]],
                tooltip=tooltip,icon=folium.Icon(color=color[year-1])).add_to(m)
    return m   

In [34]:
year1_point_interest = draw_new_points(interest1,interest0,1,m)
year1_point_cost = draw_new_points(cost1,cost0,1,m_cost)

In [35]:
def draw_station(data,m):
    for i in range(0,data.shape[0]):
        if data.iloc[i,2] >=1 and data.iloc[i,2]<=3:
            #fill_color="#F5F5F5"
            radius = 10
            color="#4682B4"
        if data.iloc[i,2] >=4 and data.iloc[i,2] <=7:
            #fill_color="#808069"
            radius = 20
            color="#0000FF"
        if data.iloc[i,2]>=8 and data.iloc[i,2]<=10:
           #fill_color="#000000"
            radius = 30
            color="#191970"

        coordinates11= np.array(data.iloc[i,:2])

        folium.CircleMarker(
            location=[coordinates11[0],coordinates11[1]],
            radius=radius,
            color=color,
            fill=False,
            fill_color="#F5F5F5",
        ).add_to(m)
    return m

In [36]:
station1 =draw_station(interest1,year1_point_interest)
station_cost1 = draw_station(cost1,year1_point_cost)
station_cost1

In [37]:
station1.save("station1_interest.html")
station_cost1.save("station1_cost.html")

In [38]:
year2_point_interest = draw_new_points(interest2,interest1,2,station1)
station2 =draw_station(interest2,year2_point_interest)

year2_point_cost = draw_new_points(cost2,cost1,2,station_cost1)
station_cost2 = draw_station(cost2,year2_point_cost)


In [39]:
station2.save("station2_interest.html")
station_cost2.save("station2_cost.html")

In [40]:
year3_point_interest = draw_new_points(interest3,interest2,3,station2)
station3 =draw_station(interest3,year3_point_interest)


year3_point_cost = draw_new_points(cost3,cost2,3,station_cost2)
station_cost3 = draw_station(cost3,year3_point_cost)

In [41]:
station3.save("station3_interest.html")
station_cost3.save("station3_cost.html")

In [42]:
year4_point_interest = draw_new_points(interest4,interest3,4,station3)
station4 =draw_station(interest4,year4_point_interest)


year4_point_cost = draw_new_points(cost4,cost3,4,station_cost3)
station_cost4 = draw_station(cost4,year4_point_cost)


In [43]:
station4.save("station4_interest.html")
station_cost4.save("station4_cost.html")